import { useState, useEffect, useCallback, useRef } from "react";

// ─────────────────────────────────────────────
//  REMINDER ENGINE — Data Model & Logic
// ─────────────────────────────────────────────

const EVENT_TYPE = { VET:"vet", VACCINE:"vaccine", WALK:"walk", BATH:"bath", MEDICATION:"medication", CUSTOM:"custom" };

const DEFAULT_REMINDERS = {
  [EVENT_TYPE.VET]:        [2, 0],
  [EVENT_TYPE.VACCINE]:    [3, 0],
  [EVENT_TYPE.WALK]:       [0],
  [EVENT_TYPE.BATH]:       [0],
  [EVENT_TYPE.MEDICATION]: [0],
  [EVENT_TYPE.CUSTOM]:     [1],
};

const EVENT_META = {
  [EVENT_TYPE.VET]:        { color:"#C8853A", icon:"🏥", label:"Vet Visit" },
  [EVENT_TYPE.VACCINE]:    { color:"#7A9E7E", icon:"💉", label:"Vaccine" },
  [EVENT_TYPE.WALK]:       { color:"#7FB5C8", icon:"🦮", label:"Walk" },
  [EVENT_TYPE.BATH]:       { color:"#A8C5A8", icon:"🛁", label:"Bath" },
  [EVENT_TYPE.MEDICATION]: { color:"#E8A090", icon:"💊", label:"Medication" },
  [EVENT_TYPE.CUSTOM]:     { color:"#8B6242", icon:"📌", label:"Reminder" },
};

function parseDate(str) { if(!str) return null; const d=new Date(str); return isNaN(d)?null:d; }
function fmtDate(d) { if(!d) return "—"; return d.toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"}); }
function daysUntil(dateStr) {
  const t=parseDate(dateStr); if(!t) return null;
  const today=new Date(); today.setHours(0,0,0,0);
  return Math.round((t-today)/86400000);
}

function makeEvent({id,petId,petName,label,date,eventType,isAutoGenerated=false,reminderTimes=null}) {
  return { id:id||Date.now(), petId, petName, label, date, eventType, isAutoGenerated,
    reminderTimes: reminderTimes ?? DEFAULT_REMINDERS[eventType] ?? [1],
    dismissed:[], createdAt:new Date().toISOString() };
}

function eventExists(events,petId,label,date) {
  return events.some(e=>e.petId===petId&&e.label===label&&e.date===date);
}

function getFiringReminders(events) {
  const today=new Date(); today.setHours(0,0,0,0);
  const results=[];
  for(const ev of events) {
    const evDate=parseDate(ev.date); if(!evDate) continue;
    const daysLeft=Math.round((evDate-today)/86400000);
    for(const offset of ev.reminderTimes) {
      if(offset===daysLeft && !ev.dismissed.includes(offset))
        results.push({event:ev,offset,daysLeft});
    }
  }
  return results;
}


// ─────────────────────────────────────────────
//  OCR ENGINE  (mock → swap in real API later)
// ─────────────────────────────────────────────

const CONF = { HIGH: "high", LOW: "low", MISSING: "missing" };

async function extractFromImage(base64Image) {
  // ── REAL API HOOK ──────────────────────────────────────────
  // Replace this mock with a real call, e.g. Claude Vision:
  //
  //   const response = await fetch("https://api.anthropic.com/v1/messages", {
  //     method: "POST",
  //     headers: { "Content-Type": "application/json" },
  //     body: JSON.stringify({
  //       model: "claude-sonnet-4-20250514",
  //       max_tokens: 1000,
  //       messages: [{ role: "user", content: [
  //         { type: "image", source: { type: "base64", media_type: "image/jpeg", data: base64Image }},
  //         { type: "text",  text: "Extract vet prescription. Return JSON only with keys: clinic, doctor, date, diagnosis, meds, nextVisit, location, reason. Each key maps to { value, confidence } where confidence is high/low/missing." }
  //       ]}]
  //     })
  //   });
  //   const data = await response.json();
  //   return JSON.parse(data.content[0].text);
  // ───────────────────────────────────────────────────────────

  await new Promise(r => setTimeout(r, 1800));
  const quality = Math.random();

  if (quality < 0.15) return null; // bad image

  if (quality < 0.35) { // partial extraction
    return {
      clinic:    { value: "PawCare Veterinary Clinic", confidence: CONF.HIGH    },
      doctor:    { value: "",                           confidence: CONF.MISSING },
      date:      { value: "",                           confidence: CONF.MISSING },
      diagnosis: { value: "Possible ear infection",    confidence: CONF.LOW     },
      meds:      { value: "Ear drops",                 confidence: CONF.LOW     },
      nextVisit: { value: "",                           confidence: CONF.MISSING },
      location:  { value: "",                           confidence: CONF.MISSING },
      reason:    { value: "",                           confidence: CONF.MISSING },
    };
  }

  const today = new Date();
  const nxt = new Date(today); nxt.setDate(nxt.getDate() + 30);
  return {
    clinic:    { value: "PawCare Veterinary Clinic",                                               confidence: CONF.HIGH },
    doctor:    { value: "Dr. Ananya Mehta",                                                        confidence: CONF.HIGH },
    date:      { value: today.toISOString().slice(0,10),                                           confidence: CONF.HIGH },
    diagnosis: { value: "Otitis externa (ear infection). No signs of systemic illness.",           confidence: CONF.HIGH },
    meds:      { value: "Otoclean Ear Drops 2x daily 7 days, Vitamin E 1 tab daily",             confidence: CONF.HIGH },
    nextVisit: { value: nxt.toISOString().slice(0,10),                                             confidence: CONF.HIGH },
    location:  { value: "MG Road, Bengaluru",                                                      confidence: CONF.LOW  },
    reason:    { value: "Ear examination",                                                         confidence: CONF.LOW  },
  };
}

function fileToBase64(file) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload  = () => resolve(reader.result.split(",")[1]);
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
}

function buildGCalURL({ title, date, description }) {
  const d = new Date(date);
  if (isNaN(d)) return null;
  const fmt = dt => dt.toISOString().replace(/[-:]/g,"").split(".")[0]+"Z";
  const start = fmt(d);
  const end   = fmt(new Date(d.getTime() + 3600000));
  const params = new URLSearchParams({ action:"TEMPLATE", text:title, dates:`${start}/${end}`, details: description||"" });
  return `https://calendar.google.com/calendar/render?${params}`;
}

// ─────────────────────────────────────────────
//  STYLES
// ─────────────────────────────────────────────
const style = `
  @import url('https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,300;0,9..144,600;0,9..144,700;1,9..144,400&family=DM+Sans:wght@300;400;500&display=swap');
  * { box-sizing:border-box; margin:0; padding:0; }
  :root {
    --cream:#FDF6EC; --warm:#F5E6CC; --amber:#C8853A; --amber-light:#E8A95A;
    --brown:#5C3D1E; --sage:#7A9E7E; --blush:#E8A090; --sky:#7FB5C8;
    --text:#2E1A0E; --text-soft:#7A5C3A;
    --card:#FFFBF5; --border:#E8D5B8; --radius:20px; --shadow:0 4px 24px rgba(90,50,10,0.08);
  }
  body { font-family:'DM Sans',sans-serif; background:var(--cream); color:var(--text); }
  .app { min-height:100vh; display:flex; flex-direction:column; max-width:430px; margin:0 auto; background:var(--cream); }

  .topbar { padding:20px 24px 0; display:flex; justify-content:space-between; align-items:center; z-index:10; position:relative; }
  .topbar-logo { font-family:'Fraunces',serif; font-size:22px; color:var(--brown); font-weight:700; letter-spacing:-0.5px; }
  .topbar-logo span { color:var(--amber); }
  .notif-btn { width:40px; height:40px; border-radius:50%; background:var(--card); border:1.5px solid var(--border); display:flex; align-items:center; justify-content:center; cursor:pointer; font-size:16px; box-shadow:var(--shadow); position:relative; }
  .notif-badge { position:absolute; top:-3px; right:-3px; width:16px; height:16px; background:#E05050; border-radius:50%; display:flex; align-items:center; justify-content:center; font-size:9px; color:white; font-weight:700; border:2px solid var(--cream); }

  .toast-stack { position:fixed; top:72px; left:50%; transform:translateX(-50%); width:calc(100% - 48px); max-width:382px; z-index:500; display:flex; flex-direction:column; gap:8px; pointer-events:none; }
  .toast { background:var(--brown); border-radius:14px; padding:12px 16px; display:flex; align-items:center; gap:12px; box-shadow:0 6px 24px rgba(40,20,5,0.22); pointer-events:all; animation:slideDown 0.3s ease; }
  @keyframes slideDown { from{opacity:0;transform:translateY(-12px)}to{opacity:1;transform:translateY(0)} }
  .toast-icon { font-size:22px; flex-shrink:0; }
  .toast-body { flex:1; }
  .toast-body strong { font-size:12px; color:white; display:block; }
  .toast-body span { font-size:11px; color:rgba(255,255,255,0.65); }
  .toast-close { font-size:16px; color:rgba(255,255,255,0.5); cursor:pointer; padding:2px 4px; flex-shrink:0; }
  .toast-close:hover { color:white; }

  .notif-panel { position:fixed; top:0; right:0; bottom:0; width:100%; max-width:430px; background:var(--cream); z-index:400; display:flex; flex-direction:column; transform:translateX(100%); transition:transform 0.3s ease; }
  .notif-panel.open { transform:translateX(0); }
  .notif-panel-header { padding:56px 24px 16px; display:flex; justify-content:space-between; align-items:center; border-bottom:1.5px solid var(--border); }
  .notif-panel-header h2 { font-family:'Fraunces',serif; font-size:22px; color:var(--brown); }
  .notif-panel-close { font-size:22px; cursor:pointer; color:var(--text-soft); }
  .notif-list { flex:1; overflow-y:auto; padding:16px 24px; display:flex; flex-direction:column; gap:10px; }
  .notif-item { background:var(--card); border:1.5px solid var(--border); border-radius:16px; padding:14px 16px; display:flex; gap:12px; align-items:flex-start; box-shadow:var(--shadow); }
  .notif-item.firing { border-color:var(--amber); background:linear-gradient(135deg,#FFF8EE,#FFF0D8); }
  .notif-dot { width:36px; height:36px; border-radius:50%; display:flex; align-items:center; justify-content:center; font-size:16px; flex-shrink:0; }
  .notif-info { flex:1; }
  .notif-info strong { font-size:13px; color:var(--brown); display:block; }
  .notif-info span { font-size:11px; color:var(--text-soft); margin-top:2px; display:block; }
  .notif-info .notif-timing { font-size:11px; font-weight:600; margin-top:4px; display:block; }
  .notif-dismiss { font-size:18px; cursor:pointer; color:var(--text-soft); flex-shrink:0; }
  .notif-dismiss:hover { color:var(--brown); }

  .screen { flex:1; display:flex; flex-direction:column; padding-bottom:90px; }
  .screen-header { padding:24px 24px 12px; }
  .screen-header h1 { font-family:'Fraunces',serif; font-size:28px; color:var(--brown); line-height:1.1; }
  .screen-header p { font-size:13px; color:var(--text-soft); margin-top:4px; }

  .pet-scroll { display:flex; gap:14px; padding:8px 24px 16px; overflow-x:auto; scrollbar-width:none; }
  .pet-scroll::-webkit-scrollbar { display:none; }
  .pet-card { min-width:150px; background:var(--card); border-radius:var(--radius); border:1.5px solid var(--border); padding:16px; cursor:pointer; box-shadow:var(--shadow); transition:transform 0.15s,box-shadow 0.15s; }
  .pet-card:hover { transform:translateY(-2px); box-shadow:0 8px 32px rgba(90,50,10,0.13); }
  .pet-card.active { border-color:var(--amber); background:linear-gradient(135deg,#FFF8EE,#FDF0D8); }
  .pet-avatar { width:56px; height:56px; border-radius:50%; background:var(--warm); display:flex; align-items:center; justify-content:center; font-size:28px; margin-bottom:10px; }
  .pet-name { font-family:'Fraunces',serif; font-size:15px; color:var(--brown); font-weight:600; }
  .pet-breed { font-size:11px; color:var(--text-soft); margin-top:2px; }
  .pet-next { margin-top:8px; font-size:10px; background:var(--warm); border-radius:8px; padding:4px 8px; color:var(--amber); font-weight:500; }
  .add-pet-card { min-width:80px; background:transparent; border:1.5px dashed var(--border); border-radius:var(--radius); padding:16px; cursor:pointer; display:flex; flex-direction:column; align-items:center; justify-content:center; gap:6px; transition:border-color 0.2s; }
  .add-pet-card:hover { border-color:var(--amber); }
  .add-pet-card span:first-child { font-size:24px; color:var(--amber); }
  .add-pet-card span:last-child { font-size:10px; color:var(--text-soft); }

  .summary-strip { margin:0 24px 20px; background:linear-gradient(135deg,var(--brown) 0%,#3A2010 100%); border-radius:var(--radius); padding:18px 20px; color:white; display:flex; gap:20px; }
  .strip-item { flex:1; }
  .strip-item label { font-size:10px; opacity:0.6; text-transform:uppercase; letter-spacing:0.8px; }
  .strip-item value { display:block; font-family:'Fraunces',serif; font-size:17px; margin-top:2px; }

  .section-title { font-family:'Fraunces',serif; font-size:17px; color:var(--brown); padding:0 24px 12px; }
  .quick-grid { display:grid; grid-template-columns:1fr 1fr; gap:12px; padding:0 24px 20px; }
  .quick-card { background:var(--card); border:1.5px solid var(--border); border-radius:var(--radius); padding:16px; cursor:pointer; box-shadow:var(--shadow); transition:transform 0.15s; }
  .quick-card:hover { transform:translateY(-1px); }
  .quick-card .qicon { font-size:24px; margin-bottom:8px; }
  .quick-card h3 { font-size:13px; font-weight:500; color:var(--brown); }
  .quick-card p { font-size:11px; color:var(--text-soft); margin-top:3px; }
  .quick-card.highlight { background:linear-gradient(135deg,#FFF3E0,#FFE0B2); border-color:var(--amber-light); }

  .upcoming-list { padding:0 24px; display:flex; flex-direction:column; gap:10px; }
  .upcoming-item { background:var(--card); border:1.5px solid var(--border); border-radius:14px; padding:14px 16px; display:flex; align-items:center; gap:14px; box-shadow:var(--shadow); }
  .upcoming-dot { width:10px; height:10px; border-radius:50%; flex-shrink:0; }
  .upcoming-info { flex:1; }
  .upcoming-info strong { font-size:13px; color:var(--brown); }
  .upcoming-info span { display:block; font-size:11px; color:var(--text-soft); margin-top:2px; }
  .upcoming-date { font-size:11px; font-weight:500; color:var(--amber); }

  .profile-hero { margin:0 24px 20px; background:linear-gradient(135deg,#5C3D1E,#3A2010); border-radius:var(--radius); padding:24px; color:white; display:flex; gap:16px; align-items:center; position:relative; }
  .profile-edit-btn { position:absolute; top:16px; right:16px; background:rgba(255,255,255,0.15); border:1px solid rgba(255,255,255,0.25); border-radius:20px; padding:5px 12px; font-size:11px; color:white; cursor:pointer; transition:background 0.15s; }
  .profile-edit-btn:hover { background:rgba(255,255,255,0.28); }
  .profile-avatar { width:72px; height:72px; border-radius:50%; background:rgba(255,255,255,0.15); display:flex; align-items:center; justify-content:center; font-size:36px; flex-shrink:0; }
  .profile-info h2 { font-family:'Fraunces',serif; font-size:24px; }
  .profile-info p { font-size:12px; opacity:0.7; margin-top:4px; }
  .profile-tags { display:flex; gap:6px; margin-top:10px; flex-wrap:wrap; }
  .tag { background:rgba(255,255,255,0.15); border-radius:20px; padding:3px 10px; font-size:10px; }

  .tabs { display:flex; padding:0 24px; gap:6px; margin-bottom:20px; overflow-x:auto; scrollbar-width:none; }
  .tabs::-webkit-scrollbar { display:none; }
  .tab { padding:8px 16px; border-radius:20px; font-size:12px; font-weight:500; border:1.5px solid var(--border); background:var(--card); color:var(--text-soft); cursor:pointer; white-space:nowrap; transition:all 0.15s; }
  .tab.active { background:var(--amber); border-color:var(--amber); color:white; }
  .tab-content { padding:0 24px; display:flex; flex-direction:column; gap:14px; }

  .visit-card { background:var(--card); border:1.5px solid var(--border); border-radius:var(--radius); padding:18px; box-shadow:var(--shadow); }
  .visit-card-header { display:flex; justify-content:space-between; align-items:flex-start; margin-bottom:14px; }
  .visit-card-header h3 { font-family:'Fraunces',serif; font-size:16px; color:var(--brown); }
  .visit-badge { font-size:10px; padding:4px 10px; border-radius:20px; font-weight:500; }
  .badge-checkup { background:#E8F5E9; color:#388E3C; }
  .badge-illness { background:#FFF3E0; color:#E65100; }
  .visit-meta { display:grid; grid-template-columns:1fr 1fr; gap:8px; margin-bottom:12px; }
  .meta-item label { font-size:10px; color:var(--text-soft); text-transform:uppercase; letter-spacing:0.5px; }
  .meta-item value { display:block; font-size:13px; color:var(--brown); margin-top:1px; }
  .diagnosis-box { background:var(--warm); border-radius:12px; padding:12px; margin-bottom:10px; }
  .diagnosis-box label { font-size:10px; color:var(--text-soft); text-transform:uppercase; letter-spacing:0.5px; }
  .diagnosis-box p { font-size:13px; color:var(--brown); margin-top:3px; }
  .meds-list { display:flex; flex-direction:column; gap:6px; }
  .med-pill { display:flex; justify-content:space-between; background:var(--cream); border-radius:10px; padding:8px 12px; }
  .med-pill span:first-child { font-size:12px; color:var(--brown); }
  .med-pill span:last-child { font-size:11px; color:var(--text-soft); }
  .upload-btn { margin-top:12px; width:100%; padding:10px; border:1.5px dashed var(--border); border-radius:12px; background:transparent; color:var(--text-soft); font-size:12px; cursor:pointer; display:flex; align-items:center; justify-content:center; gap:6px; }
  .upload-btn:hover { border-color:var(--amber); color:var(--amber); }
  .auto-event-chip { display:inline-flex; align-items:center; gap:4px; background:#E8F5E9; color:#2E7D32; border-radius:20px; padding:3px 10px; font-size:10px; font-weight:500; margin-top:8px; }

  .vaccine-stat { background:linear-gradient(135deg,var(--sage),#5A8060); border-radius:var(--radius); padding:20px; margin-bottom:14px; color:white; display:flex; gap:20px; }
  .vstat { flex:1; text-align:center; }
  .vstat-num { font-family:'Fraunces',serif; font-size:32px; }
  .vstat-label { font-size:10px; opacity:0.75; text-transform:uppercase; letter-spacing:0.5px; margin-top:2px; }
  .vaccine-item { background:var(--card); border:1.5px solid var(--border); border-radius:14px; padding:14px 16px; display:flex; gap:12px; align-items:center; box-shadow:var(--shadow); }
  .vaccine-icon { width:40px; height:40px; border-radius:50%; background:#E3F2FD; display:flex; align-items:center; justify-content:center; font-size:18px; flex-shrink:0; }
  .vaccine-info { flex:1; }
  .vaccine-info strong { font-size:13px; color:var(--brown); }
  .vaccine-info span { display:block; font-size:11px; color:var(--text-soft); margin-top:2px; }
  .vaccine-next { font-size:10px; color:var(--sage); font-weight:500; }

  .diet-current { background:linear-gradient(135deg,#FFF8EE,#FFE8C0); border:1.5px solid #F0C870; border-radius:var(--radius); padding:18px; margin-bottom:14px; }
  .diet-current label { font-size:10px; color:var(--text-soft); text-transform:uppercase; letter-spacing:0.5px; }
  .diet-current h3 { font-family:'Fraunces',serif; font-size:18px; color:var(--brown); margin-top:4px; }
  .diet-current p { font-size:12px; color:var(--text-soft); margin-top:4px; }
  .diet-change { background:var(--card); border:1.5px solid var(--border); border-radius:14px; padding:14px 16px; box-shadow:var(--shadow); }
  .diet-change-header { display:flex; justify-content:space-between; align-items:center; margin-bottom:8px; }
  .diet-change-header strong { font-size:13px; color:var(--brown); }
  .diet-change-header span { font-size:11px; color:var(--text-soft); }
  .change-to { font-size:12px; color:var(--text-soft); margin-bottom:6px; }
  .observation { background:var(--warm); border-radius:10px; padding:8px 12px; font-size:12px; color:var(--brown); }

  .exercise-ring { margin:0 auto 20px; width:140px; height:140px; position:relative; display:flex; align-items:center; justify-content:center; }
  .ring-bg { position:absolute; width:100%; height:100%; }
  .ring-center { text-align:center; z-index:1; }
  .ring-center .mins { font-family:'Fraunces',serif; font-size:32px; color:var(--brown); }
  .ring-center label { font-size:10px; color:var(--text-soft); text-transform:uppercase; letter-spacing:0.5px; }
  .walk-log { display:flex; flex-direction:column; gap:10px; }
  .walk-item { background:var(--card); border:1.5px solid var(--border); border-radius:14px; padding:14px 16px; display:flex; align-items:center; gap:12px; box-shadow:var(--shadow); }
  .walk-day { width:44px; height:44px; border-radius:12px; background:var(--warm); display:flex; flex-direction:column; align-items:center; justify-content:center; flex-shrink:0; }
  .walk-day span:first-child { font-size:16px; font-weight:600; color:var(--brown); }
  .walk-day span:last-child { font-size:9px; color:var(--text-soft); text-transform:uppercase; }
  .walk-detail { flex:1; }
  .walk-detail strong { font-size:13px; color:var(--brown); }
  .walk-detail span { display:block; font-size:11px; color:var(--text-soft); margin-top:2px; }
  .walk-mins { font-size:14px; font-weight:600; color:var(--sage); }

  .doc-grid { display:grid; grid-template-columns:1fr 1fr; gap:12px; }
  .doc-card { background:var(--card); border:1.5px solid var(--border); border-radius:var(--radius); padding:16px; box-shadow:var(--shadow); cursor:pointer; transition:transform 0.15s; }
  .doc-card:hover { transform:translateY(-2px); }
  .doc-icon { font-size:28px; margin-bottom:10px; }
  .doc-card h3 { font-size:12px; font-weight:500; color:var(--brown); }
  .doc-card p { font-size:10px; color:var(--text-soft); margin-top:3px; }
  .doc-add { background:transparent; border:1.5px dashed var(--border); display:flex; flex-direction:column; align-items:center; justify-content:center; gap:6px; }
  .doc-add span:last-child { font-size:10px; color:var(--text-soft); }

  /* ── REMINDERS SCREEN ── */
  .reminder-tabs { display:flex; gap:8px; padding:0 24px 16px; }
  .reminder-tab { padding:7px 16px; border-radius:20px; font-size:12px; font-weight:500; border:1.5px solid var(--border); background:var(--card); color:var(--text-soft); cursor:pointer; white-space:nowrap; transition:all 0.15s; }
  .reminder-tab.active { background:var(--amber); border-color:var(--amber); color:white; }
  .event-card { background:var(--card); border:1.5px solid var(--border); border-radius:16px; padding:16px; box-shadow:var(--shadow); }
  .event-card.auto { border-left:4px solid var(--sage); }
  .event-card.firing { border-color:var(--amber); background:linear-gradient(135deg,#FFFBF5,#FFF3E0); }
  .event-card-top { display:flex; align-items:center; gap:10px; margin-bottom:10px; }
  .event-type-icon { width:36px; height:36px; border-radius:50%; display:flex; align-items:center; justify-content:center; font-size:17px; flex-shrink:0; }
  .event-card-title { flex:1; }
  .event-card-title strong { font-size:14px; color:var(--brown); display:block; }
  .event-card-title span { font-size:11px; color:var(--text-soft); }
  .event-days-badge { font-size:11px; font-weight:700; padding:3px 10px; border-radius:20px; }
  .badge-soon { background:#FFF3E0; color:#C8853A; }
  .badge-today { background:#FDECEA; color:#D32F2F; }
  .badge-future { background:#F1F8E9; color:#558B2F; }
  .badge-past { background:#F5F5F5; color:#9E9E9E; }
  .event-reminder-row { display:flex; align-items:center; gap:6px; margin-top:8px; flex-wrap:wrap; }
  .reminder-chip { display:inline-flex; align-items:center; gap:4px; background:var(--warm); border-radius:20px; padding:4px 10px; font-size:11px; color:var(--text-soft); cursor:pointer; border:1.5px solid transparent; transition:all 0.15s; }
  .reminder-chip.active { background:var(--amber); color:white; border-color:var(--amber); }
  .auto-badge { font-size:9px; background:#E8F5E9; color:#2E7D32; border-radius:20px; padding:2px 8px; font-weight:600; }

  .quick-reminder-bar { padding:0 24px 16px; }
  .quick-reminder-bar h4 { font-size:13px; font-weight:600; color:var(--brown); margin-bottom:10px; }
  .quick-types { display:flex; gap:8px; flex-wrap:wrap; }
  .quick-type-btn { display:flex; align-items:center; gap:6px; padding:8px 14px; border-radius:20px; background:var(--card); border:1.5px solid var(--border); font-size:12px; color:var(--brown); cursor:pointer; transition:all 0.15s; }
  .quick-type-btn:hover { border-color:var(--amber); background:#FFF8EE; }

  .cal-header { display:flex; align-items:center; justify-content:space-between; margin-bottom:16px; }
  .cal-header h3 { font-family:'Fraunces',serif; font-size:18px; color:var(--brown); }
  .cal-nav { background:var(--card); border:1.5px solid var(--border); border-radius:8px; padding:4px 10px; cursor:pointer; font-size:16px; color:var(--brown); }
  .cal-grid { display:grid; grid-template-columns:repeat(7,1fr); gap:4px; margin-bottom:16px; }
  .cal-day-label { text-align:center; font-size:10px; color:var(--text-soft); padding:4px 0; }
  .cal-day { height:36px; border-radius:10px; display:flex; align-items:center; justify-content:center; font-size:12px; color:var(--text-soft); cursor:pointer; position:relative; }
  .cal-day.today { background:var(--amber); color:white; font-weight:600; }
  .cal-day.has-event::after { content:''; position:absolute; bottom:4px; width:4px; height:4px; border-radius:50%; background:var(--sage); }
  .cal-day.has-event.today::after { background:white; }
  .cal-events { display:flex; flex-direction:column; gap:10px; }
  .cal-event { background:var(--card); border:1.5px solid var(--border); border-radius:14px; padding:12px 16px; display:flex; gap:12px; align-items:center; box-shadow:var(--shadow); }
  .cal-event.auto-event { border-left:4px solid var(--sage); }
  .cal-event-color { width:4px; height:40px; border-radius:4px; flex-shrink:0; }
  .cal-event-info { flex:1; }
  .cal-event-info strong { font-size:13px; color:var(--brown); }
  .cal-event-info span { display:block; font-size:11px; color:var(--text-soft); margin-top:2px; }
  .cal-event-badge { font-size:9px; background:#E8F5E9; color:#2E7D32; border-radius:20px; padding:2px 7px; font-weight:600; margin-top:4px; display:inline-block; }

  .bottom-nav { position:fixed; bottom:0; left:50%; transform:translateX(-50%); width:100%; max-width:430px; background:var(--card); border-top:1.5px solid var(--border); display:flex; padding:12px 0 20px; z-index:100; box-shadow:0 -4px 24px rgba(90,50,10,0.08); }
  .nav-item { flex:1; display:flex; flex-direction:column; align-items:center; gap:4px; cursor:pointer; }
  .nav-item .nav-icon { font-size:20px; }
  .nav-item .nav-label { font-size:9px; color:var(--text-soft); }
  .nav-item.active .nav-label { color:var(--amber); font-weight:600; }
  .nav-item.active .nav-icon { filter:sepia(1) saturate(4) hue-rotate(-10deg); }

  .fab { position:fixed; bottom:90px; right:calc(50% - 215px + 20px); width:52px; height:52px; border-radius:50%; background:var(--amber); border:none; color:white; font-size:24px; cursor:pointer; box-shadow:0 6px 20px rgba(200,133,58,0.4); display:flex; align-items:center; justify-content:center; z-index:101; transition:transform 0.15s; }
  .fab:hover { transform:scale(1.05); }

  .modal-overlay { position:fixed; inset:0; background:rgba(30,15,5,0.5); z-index:200; display:flex; align-items:flex-end; justify-content:center; backdrop-filter:blur(4px); }
  .modal { background:var(--cream); border-radius:24px 24px 0 0; padding:24px; width:100%; max-width:430px; max-height:85vh; overflow-y:auto; }
  .modal h2 { font-family:'Fraunces',serif; font-size:22px; color:var(--brown); margin-bottom:20px; }
  .form-group { margin-bottom:14px; }
  .form-group label { display:block; font-size:11px; color:var(--text-soft); text-transform:uppercase; letter-spacing:0.5px; margin-bottom:6px; }
  .form-group input,.form-group select,.form-group textarea { width:100%; padding:12px 14px; border:1.5px solid var(--border); border-radius:12px; background:var(--card); color:var(--brown); font-size:13px; font-family:'DM Sans',sans-serif; outline:none; }
  .form-group input:focus,.form-group select:focus,.form-group textarea:focus { border-color:var(--amber); }
  .form-row { display:grid; grid-template-columns:1fr 1fr; gap:12px; }
  .btn-primary { width:100%; padding:14px; background:var(--amber); border:none; border-radius:14px; color:white; font-size:14px; font-weight:500; cursor:pointer; margin-top:8px; font-family:'DM Sans',sans-serif; }
  .btn-secondary { width:100%; padding:14px; background:transparent; border:1.5px solid var(--border); border-radius:14px; color:var(--text-soft); font-size:14px; cursor:pointer; margin-top:8px; font-family:'DM Sans',sans-serif; }
  .modal-handle { width:40px; height:4px; background:var(--border); border-radius:4px; margin:0 auto 20px; }
  .emoji-picker { display:flex; gap:8px; flex-wrap:wrap; margin-bottom:16px; }
  .emoji-opt { font-size:24px; cursor:pointer; padding:6px 8px; border-radius:10px; border:1.5px solid transparent; transition:all 0.15s; }
  .emoji-opt.selected { background:var(--warm); border-color:var(--amber); }
  .offset-picker { display:flex; gap:8px; flex-wrap:wrap; margin-top:6px; }
  .offset-chip { padding:6px 14px; border-radius:20px; font-size:12px; border:1.5px solid var(--border); background:var(--card); color:var(--text-soft); cursor:pointer; transition:all 0.15s; }
  .offset-chip.on { background:var(--amber); border-color:var(--amber); color:white; }
  .empty-state { text-align:center; padding:40px 20px; color:var(--text-soft); }
  .empty-state .es-icon { font-size:48px; margin-bottom:12px; }
  .empty-state p { font-size:13px; }
  .info-banner { margin:0 24px 16px; background:linear-gradient(135deg,#E8F5E9,#F1F8E9); border:1.5px solid #A8D5A8; border-radius:14px; padding:12px 16px; display:flex; gap:10px; align-items:flex-start; }
  .info-banner span { font-size:12px; color:#2E7D32; flex:1; }
  /* ── SCAN / OCR STYLES ── */
  .scan-btns { display:flex; gap:10px; margin-bottom:18px; }
  .scan-btn { flex:1; padding:11px 8px; border-radius:14px; border:1.5px solid var(--border); background:var(--card); color:var(--brown); font-size:12px; font-weight:500; cursor:pointer; display:flex; align-items:center; justify-content:center; gap:7px; transition:all 0.15s; font-family:'DM Sans',sans-serif; }
  .scan-btn:hover { border-color:var(--amber); background:#FFF8EE; color:var(--amber); }
  .scan-btn.primary { background:var(--amber); border-color:var(--amber); color:white; }
  .scan-btn.primary:hover { background:#B8742A; }
  .scan-preview { position:relative; margin-bottom:16px; border-radius:14px; overflow:hidden; border:1.5px solid var(--border); }
  .scan-preview img { width:100%; max-height:180px; object-fit:cover; display:block; }
  .scan-preview-remove { position:absolute; top:8px; right:8px; width:28px; height:28px; border-radius:50%; background:rgba(0,0,0,0.55); border:none; color:white; font-size:14px; cursor:pointer; display:flex; align-items:center; justify-content:center; }
  .scan-processing { display:flex; align-items:center; gap:10px; background:linear-gradient(135deg,#EEF5FF,#E8F0FF); border:1.5px solid #BDD0FF; border-radius:14px; padding:14px 16px; margin-bottom:16px; }
  .scan-spinner { width:22px; height:22px; border:3px solid #BDD0FF; border-top-color:#4A7AE8; border-radius:50%; animation:spin 0.8s linear infinite; flex-shrink:0; }
  @keyframes spin { to { transform:rotate(360deg); } }
  .scan-processing span { font-size:12px; color:#2A4CB0; }
  .scan-result-banner { border-radius:12px; padding:10px 14px; margin-bottom:14px; display:flex; align-items:center; gap:8px; font-size:12px; }
  .scan-result-banner.success { background:#E8F5E9; border:1.5px solid #A8D5A8; color:#2E7D32; }
  .scan-result-banner.warn    { background:#FFF8E1; border:1.5px solid #FFE082; color:#795500; }
  .scan-result-banner.error   { background:#FDECEA; border:1.5px solid #FFCDD2; color:#B71C1C; }
  .field-low-conf input, .field-low-conf textarea { border-color:#F0B429 !important; background:#FFFDE7 !important; }
  .field-low-conf label { color:#795500 !important; }
  .field-warn-msg { font-size:10px; color:#795500; margin-top:4px; display:flex; align-items:center; gap:4px; }
  .field-autofilled input, .field-autofilled textarea { border-color:var(--sage) !important; background:#F1F8F2 !important; }
  .field-autofilled label::after { content:' ✦'; color:var(--sage); font-size:9px; }
  .ocr-divider { display:flex; align-items:center; gap:10px; margin:14px 0; }
  .ocr-divider span { font-size:11px; color:var(--text-soft); white-space:nowrap; }
  .ocr-divider::before,.ocr-divider::after { content:''; flex:1; height:1px; background:var(--border); }
  .gcal-btn { display:flex; align-items:center; justify-content:center; gap:8px; width:100%; padding:11px; border:1.5px solid #4285F4; border-radius:12px; background:white; color:#4285F4; font-size:13px; font-weight:500; cursor:pointer; margin-top:8px; font-family:'DM Sans',sans-serif; transition:all 0.15s; }
  .gcal-btn:hover { background:#EEF4FF; }
  .gcal-btn svg { flex-shrink:0; }
  .review-badge { display:inline-flex; align-items:center; gap:5px; background:#FFF3E0; border:1px solid #FFB74D; border-radius:20px; padding:4px 12px; font-size:11px; color:#E65100; font-weight:500; margin-bottom:14px; }
  /* ── PUSH NOTIFICATION PERMISSION UI ── */
  .push-banner { margin:0 24px 16px; background:linear-gradient(135deg,#5C3D1E,#3A2010); border-radius:16px; padding:16px 18px; display:flex; gap:14px; align-items:center; }
  .push-banner-icon { font-size:28px; flex-shrink:0; }
  .push-banner-text { flex:1; }
  .push-banner-text strong { font-size:13px; color:white; display:block; margin-bottom:3px; }
  .push-banner-text span { font-size:11px; color:rgba(255,255,255,0.65); }
  .push-enable-btn { padding:8px 14px; background:var(--amber); border:none; border-radius:10px; color:white; font-size:12px; font-weight:600; cursor:pointer; font-family:'DM Sans',sans-serif; white-space:nowrap; flex-shrink:0; }
  .push-status-row { margin:0 24px 12px; display:flex; align-items:center; gap:8px; }
  .push-dot { width:8px; height:8px; border-radius:50%; flex-shrink:0; }
  .push-dot.on  { background:#4CAF50; box-shadow:0 0 6px #4CAF5088; }
  .push-dot.off { background:#9E9E9E; }
  .push-status-row span { font-size:11px; color:var(--text-soft); }
  .push-status-row button { margin-left:auto; font-size:11px; color:var(--amber); background:none; border:none; cursor:pointer; font-family:'DM Sans',sans-serif; }
  .notif-schedule-row { margin-top:10px; padding:10px 14px; background:var(--warm); border-radius:10px; display:flex; align-items:center; gap:8px; }
  .notif-schedule-row span { font-size:11px; color:var(--text-soft); flex:1; }
  .notif-schedule-row strong { font-size:11px; color:var(--brown); }

`;

// ─────────────────────────────────────────────
//  SEED DATA
// ─────────────────────────────────────────────
const EMOJIS = ["🐶","🐱","🐰","🐦","🐠","🐇","🐹","🦜"];
const OFFSET_OPTIONS = [0,1,2,3,7];
const OFFSET_LABEL   = {0:"Same day",1:"1 day before",2:"2 days before",3:"3 days before",7:"1 week before"};

const now   = new Date();
const iso   = d => d.toISOString().slice(0,10);
const shift = n => { const d=new Date(now); d.setDate(d.getDate()+n); return d; };

const initialPets = [
  { id:1, name:"Dora",   emoji:"🐶", breed:"Adult Dog", age:"2 yrs",      gender:"Female", birthday:"Feb 22, 2024", nextVet:"Mar 25, 2026" },
  { id:2, name:"Scooby", emoji:"🐶", breed:"Puppy",     age:"1.5 months", gender:"Male",   birthday:"Jan 7, 2026",  nextVet:"Apr 18, 2026" },
];

const initialEvents = [
  makeEvent({id:1, petId:1, petName:"Dora",   label:"Vet Visit – PawCare Clinic",  date:iso(shift(6)),  eventType:EVENT_TYPE.VET,      isAutoGenerated:true}),
  makeEvent({id:2, petId:1, petName:"Dora",   label:"Grooming",                    date:iso(shift(15)), eventType:EVENT_TYPE.BATH,     isAutoGenerated:false}),
  makeEvent({id:3, petId:1, petName:"Dora",   label:"DHPP Booster due",            date:iso(shift(9)),  eventType:EVENT_TYPE.VACCINE,  isAutoGenerated:true}),
  makeEvent({id:4, petId:2, petName:"Scooby", label:"Vaccine – DHPPi 2nd dose",    date:iso(shift(3)),  eventType:EVENT_TYPE.VACCINE,  isAutoGenerated:true}),
  makeEvent({id:5, petId:2, petName:"Scooby", label:"Vet Visit – City Paws",       date:iso(shift(0)),  eventType:EVENT_TYPE.VET,      isAutoGenerated:true}),
  makeEvent({id:6, petId:1, petName:"Dora",   label:"Morning Walk",                date:iso(shift(1)),  eventType:EVENT_TYPE.WALK,     isAutoGenerated:false}),
];

const initialVetVisits = {
  1:[
    {id:1,date:"Jan 15, 2026",clinic:"PawCare Clinic",location:"MG Road, Bengaluru",doctor:"Dr. Ananya Mehta",reason:"Annual Checkup",type:"checkup",diagnosis:"Generally healthy. Mild ear infection.",meds:[{name:"Otoclean Ear Drops",schedule:"2x daily, 7 days"}],nextVisit:iso(shift(6)),hasReport:true},
    {id:2,date:"Aug 20, 2025",clinic:"Happy Paws Vet",location:"Indiranagar, Bengaluru",doctor:"Dr. Rajan Pillai",reason:"Upset stomach",type:"illness",diagnosis:"Mild gastritis.",meds:[{name:"Metronidazole",schedule:"1x daily, 5 days"}],nextVisit:"",hasReport:false}
  ],
  2:[
    {id:1,date:"Feb 10, 2026",clinic:"City Paws Clinic",location:"Koramangala, Bengaluru",doctor:"Dr. Priya Sharma",reason:"First Puppy Visit",type:"checkup",diagnosis:"Healthy. Started vaccination.",meds:[],nextVisit:iso(shift(0)),hasReport:false}
  ]
};

const initialVaccines = {
  1:[
    {id:1,name:"Rabies",       date:"Jan 15, 2026",clinic:"PawCare Clinic",doctor:"Ananya Mehta", nextDue:iso(shift(9))},
    {id:2,name:"DHPP (Combo)", date:"Jan 15, 2026",clinic:"PawCare Clinic",doctor:"Ananya Mehta", nextDue:iso(shift(40))},
    {id:3,name:"Bordetella",   date:"Aug 2025",     clinic:"Happy Paws",   doctor:"Rajan Pillai", nextDue:iso(shift(140))},
  ],
  2:[
    {id:1,name:"DHPPi (1st)",  date:"Feb 10, 2026", clinic:"City Paws",    doctor:"Priya Sharma", nextDue:iso(shift(3))},
  ]
};

const initialDiet = {
  1:{current:{food:"Royal Canin Adult",type:"Dry Kibble",since:"Sep 2025"},history:[{id:1,date:"Sep 1, 2025",from:"Pedigree Adult",to:"Royal Canin Adult",observation:"Improved coat shine. Firmer stools."}]},
  2:{current:{food:"Royal Canin Puppy",type:"Dry Kibble + Wet",since:"Jan 2026"},history:[]}
};

const initialExercise = {
  1:[{id:1,day:22,dayName:"Sun",duration:45,route:"Cubbon Park loop",time:"6:30 AM"},{id:2,day:21,dayName:"Sat",duration:60,route:"Long trail",time:"6:00 AM"},{id:3,day:20,dayName:"Fri",duration:30,route:"Neighbourhood",time:"7:00 AM"}],
  2:[]
};

const initialDocs = {
  1:[{id:1,name:"Adoption Papers",icon:"📄",date:"Feb 2024",size:"1.2 MB"},{id:2,name:"Insurance Policy",icon:"🛡️",date:"Jan 2026",size:"340 KB"},{id:3,name:"Vet Report",icon:"🏥",date:"Jan 2026",size:"2.1 MB"}],
  2:[{id:1,name:"Puppy Health Card",icon:"📋",date:"Feb 2026",size:"450 KB"}]
};


// ─────────────────────────────────────────────
//  LOCALSTORAGE PERSISTENCE
//  Versioned so future schema changes can migrate
// ─────────────────────────────────────────────
const LS_VERSION = "pk_v1";
const LS_KEYS = {
  pets:       "pk_v1_pets",
  vetVisits:  "pk_v1_vetVisits",
  events:     "pk_v1_events",
  activePet:  "pk_v1_activePet",
};

function lsGet(key, fallback) {
  try {
    const raw = localStorage.getItem(key);
    return raw ? JSON.parse(raw) : fallback;
  } catch { return fallback; }
}

function lsSet(key, value) {
  try { localStorage.setItem(key, JSON.stringify(value)); } catch {}
}

// Hydrate initial state — use saved data if available, seed data otherwise
function hydrateState() {
  return {
    pets:      lsGet(LS_KEYS.pets,      initialPets),
    vetVisits: lsGet(LS_KEYS.vetVisits, initialVetVisits),
    events:    lsGet(LS_KEYS.events,    initialEvents),
    activePet: lsGet(LS_KEYS.activePet, 1),
  };
}


// ─────────────────────────────────────────────
//  PUSH NOTIFICATION ENGINE
// ─────────────────────────────────────────────

// Register the service worker once on app load
async function registerSW() {
  if (!("serviceWorker" in navigator)) return null;
  try {
    const reg = await navigator.serviceWorker.register("/sw.js", { scope: "/" });
    await navigator.serviceWorker.ready;
    return reg;
  } catch(e) {
    console.warn("SW registration failed:", e);
    return null;
  }
}

// Request notification permission — returns "granted" | "denied" | "default"
async function requestPermission() {
  if (!("Notification" in window)) return "unsupported";
  if (Notification.permission === "granted") return "granted";
  return await Notification.requestPermission();
}

// Build the list of notifications to schedule from all events
// Each event × each offset produces one notification entry
function buildNotificationList(events) {
  const list = [];
  const today = new Date(); today.setHours(0,0,0,0);

  for (const ev of events) {
    const evDate = parseDate(ev.date);
    if (!evDate) continue;

    for (const offset of ev.reminderTimes) {
      const fireDate = new Date(evDate);
      fireDate.setDate(fireDate.getDate() - offset);
      fireDate.setHours(9, 0, 0, 0); // fire at 9 AM on reminder day

      if (fireDate <= new Date()) continue; // skip past

      const meta = EVENT_META[ev.eventType] || EVENT_META["custom"];
      const whenLabel = offset === 0 ? "today" : offset === 1 ? "tomorrow" : `in ${offset} days`;

      list.push({
        tag:    `pk-${ev.id}-${offset}`,
        fireAt: fireDate.getTime(),
        title:  `${meta.icon} ${ev.label}`,
        body:   `${ev.petName}'s ${meta.label.toLowerCase()} is ${whenLabel} — ${new Date(ev.date).toLocaleDateString("en-US",{month:"short",day:"numeric"})}`,
      });
    }
  }
  return list;
}

// Send schedule to service worker
async function syncNotificationsToSW(events) {
  if (!("serviceWorker" in navigator)) return 0;
  const reg = await navigator.serviceWorker.ready;
  if (!reg.active) return 0;
  const list = buildNotificationList(events);
  reg.active.postMessage({ type: "SCHEDULE_NOTIFICATIONS", notifications: list });
  return list.length;
}

// ─────────────────────────────────────────────
//  APP COMPONENT
// ─────────────────────────────────────────────
export default function PawKeeper() {
  const hydrated = useRef(hydrateState());
  const [activeNav,       setActiveNav]       = useState("home");
  const [activePet,       setActivePet]       = useState(()=>hydrated.current.activePet);
  const [activeTab,       setActiveTab]       = useState("vet");
  const [reminderSubTab,  setReminderSubTab]  = useState("upcoming");
  const [pets,            setPets]            = useState(()=>hydrated.current.pets);
  const [vetVisits,       setVetVisits]       = useState(()=>hydrated.current.vetVisits);
  const [vaccines]                            = useState(initialVaccines);
  const [diet]                                = useState(initialDiet);
  const [exercise]                            = useState(initialExercise);
  const [docs]                                = useState(initialDocs);
  const [events,          setEvents]          = useState(()=>hydrated.current.events);
  const [toasts,          setToasts]          = useState([]);
  const [dismissedSet,    setDismissedSet]    = useState(new Set());
  const [notifOpen,       setNotifOpen]       = useState(false);
  const [showModal,       setShowModal]       = useState(null);
  const [newVet,          setNewVet]          = useState({date:"",clinic:"",location:"",doctor:"",reason:"",diagnosis:"",meds:"",nextVisit:""});
  const [newPet,          setNewPet]          = useState({name:"",breed:"",age:"",gender:"Male",birthday:"",emoji:"🐶"});
  const [editPetData,     setEditPetData]     = useState(null);
  const [newReminder,     setNewReminder]     = useState({label:"",date:"",petId:1,eventType:EVENT_TYPE.CUSTOM,reminderTimes:[1]});

  // ── PUSH NOTIFICATION state ──
  const [pushPermission,  setPushPermission]  = useState(()=> "Notification" in window ? Notification.permission : "unsupported");
  const [pushScheduled,   setPushScheduled]   = useState(0);   // count of scheduled notifications
  const swRegistered      = useRef(false);

  // ── SCAN / OCR state ──
  const [scanState,       setScanState]       = useState("idle"); // idle | processing | done | error
  const [scanImageURL,    setScanImageURL]     = useState(null);   // preview URL
  const [ocrResult,       setOcrResult]       = useState(null);   // extracted fields map
  const [ocrFields,       setOcrFields]       = useState({});     // { fieldName: confidence }

  const pet         = pets.find(p=>p.id===activePet);
  const petVisits   = vetVisits[activePet]||[];
  const petVaccines = vaccines[activePet]||[];
  const petDiet     = diet[activePet];
  const petExercise = exercise[activePet]||[];
  const petDocs     = docs[activePet]||[];
  const avgWalk     = petExercise.length ? Math.round(petExercise.reduce((a,b)=>a+b.duration,0)/petExercise.length) : 0;


  // ── PERSIST TO LOCALSTORAGE on every change ──
  useEffect(()=>{ lsSet(LS_KEYS.pets,      pets);      }, [pets]);
  useEffect(()=>{ lsSet(LS_KEYS.vetVisits, vetVisits); }, [vetVisits]);
  useEffect(()=>{ lsSet(LS_KEYS.events,    events);    }, [events]);
  useEffect(()=>{ lsSet(LS_KEYS.activePet, activePet); }, [activePet]);

  // ── SERVICE WORKER REGISTRATION ──
  useEffect(()=>{
    if (swRegistered.current) return;
    swRegistered.current = true;
    registerSW().then(reg => {
      if (!reg) return;
      // Listen for SW acknowledgement
      navigator.serviceWorker.addEventListener("message", e => {
        if (e.data?.type === "SCHEDULED") setPushScheduled(e.data.count);
      });
      // Sync if already have permission
      if (Notification.permission === "granted") {
        syncNotificationsToSW(events).then(n => setPushScheduled(n));
      }
    });
  }, []); // eslint-disable-line

  // ── RE-SYNC NOTIFICATIONS whenever events change ──
  useEffect(()=>{
    if (Notification.permission !== "granted") return;
    syncNotificationsToSW(events).then(n => setPushScheduled(n));
  }, [events]);

  // ── AUTO-EVENT CREATION ──
  const autoCreateEvent = useCallback((petId, petName, label, date, eventType) => {
    if(!date) return;
    setEvents(prev => {
      if(eventExists(prev,petId,label,date)) return prev;
      return [...prev, makeEvent({petId,petName,label,date,eventType,isAutoGenerated:true})];
    });
  }, []);

  // ── FIRE REMINDERS ON MOUNT ──
  useEffect(()=>{
    const firing = getFiringReminders(events)
      .filter(f=>!dismissedSet.has(`${f.event.id}-${f.offset}`))
      .slice(0,3);
    if(firing.length) setToasts(firing.map(f=>({id:`${f.event.id}-${f.offset}`,event:f.event,offset:f.offset,daysLeft:f.daysLeft})));
  },[]); // eslint-disable-line

  const dismissToast = id => {
    setDismissedSet(prev=>new Set([...prev,id]));
    setToasts(prev=>prev.filter(t=>t.id!==id));
    const [evId,offset] = id.split("-");
    setEvents(prev=>prev.map(e=>e.id===parseInt(evId)?{...e,dismissed:[...e.dismissed,parseInt(offset)]}:e));
  };

  const firingCount = getFiringReminders(events).filter(f=>!dismissedSet.has(`${f.event.id}-${f.offset}`)).length;

  const toggleOffset = (eventId,offset) => {
    setEvents(prev=>prev.map(e=>{
      if(e.id!==eventId) return e;
      const has=e.reminderTimes.includes(offset);
      return{...e,reminderTimes:has?e.reminderTimes.filter(o=>o!==offset):[...e.reminderTimes,offset]};
    }));
  };

  const daysLabel = dateStr => {
    const d=daysUntil(dateStr);
    if(d===null) return null;
    if(d<0)  return{text:`${Math.abs(d)}d ago`,cls:"badge-past"};
    if(d===0)return{text:"Today!",cls:"badge-today"};
    if(d<=3) return{text:`In ${d}d`,cls:"badge-soon"};
    return{text:`In ${d}d`,cls:"badge-future"};
  };

  const sortedEvents   = [...events].sort((a,b)=>new Date(a.date)-new Date(b.date));
  const upcomingEvents = sortedEvents.filter(e=>daysUntil(e.date)>=0);

  // ── HANDLERS ──
  const handleAddVet = () => {
    if(!newVet.date||!newVet.clinic) return;
    const visit={id:Date.now(),...newVet,type:"checkup",meds:newVet.meds?newVet.meds.split(",").map(m=>({name:m.trim(),schedule:"As prescribed"})):[],hasReport:false};
    setVetVisits(v=>({...v,[activePet]:[visit,...(v[activePet]||[])]}));
    if(newVet.nextVisit) autoCreateEvent(activePet,pet.name,`Vet Visit – ${newVet.clinic}`,newVet.nextVisit,EVENT_TYPE.VET);
    setNewVet({date:"",clinic:"",location:"",doctor:"",reason:"",diagnosis:"",meds:"",nextVisit:""});
    resetScan();
    setShowModal(null);
  };

  // ── PUSH NOTIFICATION HANDLER ──
  const handleEnablePush = async () => {
    const permission = await requestPermission();
    setPushPermission(permission);
    if (permission === "granted") {
      await registerSW();
      const n = await syncNotificationsToSW(events);
      setPushScheduled(n);
    }
  };

  // ── OCR / SCAN HANDLERS ──
  const resetScan = () => {
    setScanState("idle"); setScanImageURL(null); setOcrResult(null); setOcrFields({});
  };

  const handleImageFile = async (file) => {
    if (!file) return;
    const url = URL.createObjectURL(file);
    setScanImageURL(url);
    setScanState("processing");
    try {
      const b64 = await fileToBase64(file);
      const result = await extractFromImage(b64);
      if (!result) {
        setScanState("error");
        return;
      }
      // Autofill form fields from OCR result
      const confidenceMap = {};
      setNewVet(v => {
        const updated = { ...v };
        const map = { clinic:"clinic", doctor:"doctor", date:"date", diagnosis:"diagnosis", meds:"meds", nextVisit:"nextVisit", location:"location", reason:"reason" };
        Object.entries(map).forEach(([ocrKey, formKey]) => {
          if (result[ocrKey] && result[ocrKey].value) {
            updated[formKey] = result[ocrKey].value;
            confidenceMap[formKey] = result[ocrKey].confidence;
          } else {
            confidenceMap[formKey] = CONF.MISSING;
          }
        });
        return updated;
      });
      setOcrFields(confidenceMap);
      setOcrResult(result);
      setScanState("done");
    } catch(e) {
      setScanState("error");
    }
  };

  const handleScanCamera = () => {
    const input = document.createElement("input");
    input.type = "file"; input.accept = "image/*"; input.capture = "environment";
    input.onchange = e => handleImageFile(e.target.files[0]);
    input.click();
  };

  const handleScanUpload = () => {
    const input = document.createElement("input");
    input.type = "file"; input.accept = "image/*,application/pdf";
    input.onchange = e => handleImageFile(e.target.files[0]);
    input.click();
  };

  // Field class helper: returns css class based on OCR confidence
  const fieldClass = (key) => {
    if (!ocrResult) return "";
    const c = ocrFields[key];
    if (c === CONF.HIGH)    return "field-autofilled";
    if (c === CONF.LOW)     return "field-low-conf";
    return "";
  };

  const handleAddPet = () => {
    if(!newPet.name) return;
    const id=Date.now();
    setPets(p=>[...p,{id,...newPet}]);
    setNewPet({name:"",breed:"",age:"",gender:"Male",birthday:"",emoji:"🐶"});
    setActivePet(id); setShowModal(null);
  };

  const handleSaveEditPet = () => {
    if(!editPetData?.name) return;
    setPets(p=>p.map(x=>x.id===activePet?{...x,...editPetData}:x));
    setEditPetData(null); setShowModal(null);
  };

  const handleAddReminder = () => {
    if(!newReminder.label||!newReminder.date) return;
    const petObj=pets.find(p=>p.id===newReminder.petId);
    setEvents(prev=>[...prev,makeEvent({petId:newReminder.petId,petName:petObj?.name||"",label:newReminder.label,date:newReminder.date,eventType:newReminder.eventType,reminderTimes:newReminder.reminderTimes})]);
    setNewReminder({label:"",date:"",petId:1,eventType:EVENT_TYPE.CUSTOM,reminderTimes:[1]});
    setShowModal(null);
  };

  // ─────────────────────────────────────────────
  //  EVENT CARD (reusable)
  // ─────────────────────────────────────────────
  const EventCard = ({ev}) => {
    const meta = EVENT_META[ev.eventType]||EVENT_META[EVENT_TYPE.CUSTOM];
    const dl   = daysLabel(ev.date);
    const isFiring = getFiringReminders([ev]).filter(f=>!dismissedSet.has(`${f.event.id}-${f.offset}`)).length>0;
    return (
      <div className={`event-card ${ev.isAutoGenerated?"auto":""} ${isFiring?"firing":""}`}>
        <div className="event-card-top">
          <div className="event-type-icon" style={{background:meta.color+"22"}}>{meta.icon}</div>
          <div className="event-card-title">
            <strong>{ev.label}</strong>
            <span>{ev.petName} · {fmtDate(parseDate(ev.date))}</span>
          </div>
          <div style={{display:"flex",flexDirection:"column",alignItems:"flex-end",gap:4,flexShrink:0}}>
            {dl&&<span className={`event-days-badge ${dl.cls}`}>{dl.text}</span>}
            {ev.isAutoGenerated&&<span className="auto-badge">Auto</span>}
          </div>
        </div>
        <div className="event-reminder-row">
          <span style={{fontSize:10,color:"var(--text-soft)",flexShrink:0}}>🔔</span>
          {OFFSET_OPTIONS.map(o=>(
            <span key={o} className={`reminder-chip ${ev.reminderTimes.includes(o)?"active":""}`}
              onClick={()=>toggleOffset(ev.id,o)}>
              {OFFSET_LABEL[o]}
            </span>
          ))}
        </div>
      </div>
    );
  };

  // ─────────────────────────────────────────────
  //  SCREENS
  // ─────────────────────────────────────────────
  const renderHome = () => (
    <div className="screen">
      <div className="screen-header">
        <h1>Your Pets 🐾</h1>
        <p>{new Date().toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric",year:"numeric"})}</p>
      </div>
      <div className="pet-scroll">
        {pets.map(p=>(
          <div key={p.id} className={`pet-card ${activePet===p.id?"active":""}`} onClick={()=>{setActivePet(p.id);setActiveNav("profile");}}>
            <div className="pet-avatar">{p.emoji}</div>
            <div className="pet-name">{p.name}</div>
            <div className="pet-breed">{p.breed}</div>
            <div className="pet-next">Next vet: {p.nextVet||"—"}</div>
          </div>
        ))}
        <div className="add-pet-card" onClick={()=>setShowModal("addPet")}><span>＋</span><span>Add Pet</span></div>
      </div>
      {pet&&<div className="summary-strip">
        <div className="strip-item"><label>Name</label><value>{pet.name}</value></div>
        <div className="strip-item"><label>Age</label><value>{pet.age}</value></div>
        <div className="strip-item"><label>Gender</label><value>{pet.gender}</value></div>
      </div>}
      <div className="section-title">Upcoming 📅</div>
      <div className="upcoming-list" style={{marginBottom:20}}>
        {upcomingEvents.slice(0,4).map(ev=>{
          const meta=EVENT_META[ev.eventType]||EVENT_META[EVENT_TYPE.CUSTOM];
          const dl=daysLabel(ev.date);
          return(
            <div key={ev.id} className="upcoming-item">
              <div className="upcoming-dot" style={{background:meta.color}}></div>
              <div className="upcoming-info">
                <strong>{ev.label}</strong>
                <span>{ev.petName} · {fmtDate(parseDate(ev.date))}{ev.isAutoGenerated?" · 🤖 Auto":""}</span>
              </div>
              {dl&&<div className="upcoming-date">{dl.text}</div>}
            </div>
          );
        })}
        {upcomingEvents.length===0&&<div style={{padding:"12px 0",color:"var(--text-soft)",fontSize:13,textAlign:"center"}}>No upcoming events</div>}
      </div>
      <div className="section-title">Quick Access</div>
      <div className="quick-grid">
        <div className="quick-card highlight" onClick={()=>{setActiveNav("profile");setActiveTab("vet");}}>
          <div className="qicon">🏥</div><h3>Vet Visits</h3><p>{petVisits.length} records</p>
        </div>
        <div className="quick-card" onClick={()=>{setActiveNav("profile");setActiveTab("vaccine");}}>
          <div className="qicon">💉</div><h3>Vaccines</h3><p>{petVaccines.length} on record</p>
        </div>
        <div className="quick-card" onClick={()=>{setActiveNav("profile");setActiveTab("diet");}}>
          <div className="qicon">🍽️</div><h3>Diet</h3><p>{petDiet?.current?.food?.split(" ").slice(0,3).join(" ")}</p>
        </div>
        <div className="quick-card" onClick={()=>setActiveNav("reminders")}>
          <div className="qicon">🔔</div><h3>Reminders</h3><p>{upcomingEvents.length} upcoming{firingCount>0?` · ${firingCount} firing!`:""}</p>
        </div>
      </div>
    </div>
  );

  const renderProfile = () => (
    <div className="screen">
      <div className="profile-hero">
        <div className="profile-avatar">{pet?.emoji}</div>
        <div className="profile-info">
          <h2>{pet?.name}</h2>
          <p>{pet?.breed} · Born {pet?.birthday}</p>
          <div className="profile-tags">
            <span className="tag">{pet?.age}</span>
            <span className="tag">{pet?.gender}</span>
            <span className="tag">Next vet: {pet?.nextVet}</span>
          </div>
        </div>
        <button className="profile-edit-btn" onClick={()=>{setEditPetData({...pet});setShowModal("editPet");}}>✏️ Edit</button>
      </div>
      <div className="tabs">
        {[["vet","🏥 Vet"],["vaccine","💉 Vaccines"],["diet","🍽️ Diet"],["exercise","🦮 Exercise"]].map(([k,l])=>(
          <div key={k} className={`tab ${activeTab===k?"active":""}`} onClick={()=>setActiveTab(k)}>{l}</div>
        ))}
      </div>
      <div className="tab-content">
        {activeTab==="vet"&&(
          <>
            {petVisits.length===0&&<div className="empty-state"><div className="es-icon">🏥</div><p>No vet visits yet.<br/>Tap + to log one.</p></div>}
            {petVisits.map(v=>(
              <div key={v.id} className="visit-card">
                <div className="visit-card-header">
                  <h3>{v.clinic}</h3>
                  <span className={`visit-badge badge-${v.type}`}>{v.reason}</span>
                </div>
                <div className="visit-meta">
                  <div className="meta-item"><label>Date</label><value>{v.date}</value></div>
                  <div className="meta-item"><label>Doctor</label><value>{v.doctor}</value></div>
                  <div className="meta-item"><label>Location</label><value>{v.location}</value></div>
                  <div className="meta-item"><label>Next Visit</label><value>{v.nextVisit?fmtDate(parseDate(v.nextVisit)):"—"}</value></div>
                </div>
                {v.diagnosis&&<div className="diagnosis-box"><label>Diagnosis</label><p>{v.diagnosis}</p></div>}
                {v.meds?.length>0&&<><div style={{fontSize:10,color:"var(--text-soft)",textTransform:"uppercase",letterSpacing:"0.5px",marginBottom:6}}>Medications</div>
                <div className="meds-list">{v.meds.map((m,i)=><div key={i} className="med-pill"><span>💊 {m.name}</span><span>{m.schedule}</span></div>)}</div></>}
                {v.nextVisit&&events.some(e=>e.petId===activePet&&e.date===v.nextVisit&&e.eventType===EVENT_TYPE.VET)&&
                  <div className="auto-event-chip">✅ Calendar reminder auto-created</div>}
                <button className="upload-btn">📎 {v.hasReport?"View Report":"Upload Report"}</button>
              </div>
            ))}
          </>
        )}
        {activeTab==="vaccine"&&(
          <>
            <div className="vaccine-stat">
              <div className="vstat"><div className="vstat-num">{petVaccines.length}</div><div className="vstat-label">Total Vaccines</div></div>
              <div className="vstat"><div className="vstat-num">2026</div><div className="vstat-label">Last Updated</div></div>
            </div>
            {petVaccines.map(v=>(
              <div key={v.id} className="vaccine-item">
                <div className="vaccine-icon">💉</div>
                <div className="vaccine-info">
                  <strong>{v.name}</strong>
                  <span>{v.date} · {v.clinic}</span>
                  <span>Dr. {v.doctor}</span>
                  {events.some(e=>e.petId===activePet&&e.date===v.nextDue&&e.eventType===EVENT_TYPE.VACCINE)&&
                    <span style={{fontSize:10,color:"var(--sage)",fontWeight:600,marginTop:3,display:"block"}}>✅ Reminder scheduled</span>}
                </div>
                <div className="vaccine-next">Due {fmtDate(parseDate(v.nextDue))}</div>
              </div>
            ))}
          </>
        )}
        {activeTab==="diet"&&petDiet&&(
          <>
            <div className="diet-current">
              <label>Current Diet</label>
              <h3>{petDiet.current.food}</h3>
              <p>{petDiet.current.type} · Since {petDiet.current.since}</p>
            </div>
            <div style={{fontSize:13,fontWeight:500,color:"var(--brown)",marginBottom:10}}>Diet History</div>
            {petDiet.history.length===0&&<div className="empty-state"><div className="es-icon">🍽️</div><p>No changes logged.</p></div>}
            {petDiet.history.map(h=>(
              <div key={h.id} className="diet-change">
                <div className="diet-change-header"><strong>Changed Diet</strong><span>{h.date}</span></div>
                <div className="change-to">From <em>{h.from}</em> → <strong>{h.to}</strong></div>
                <div className="observation">🔍 {h.observation}</div>
              </div>
            ))}
          </>
        )}
        {activeTab==="exercise"&&(
          <>
            <div className="exercise-ring">
              <svg className="ring-bg" viewBox="0 0 140 140">
                <circle cx="70" cy="70" r="58" fill="none" stroke="#E8D5B8" strokeWidth="12"/>
                <circle cx="70" cy="70" r="58" fill="none" stroke="#7A9E7E" strokeWidth="12"
                  strokeDasharray={`${Math.min((avgWalk/60)*364,364)} 364`} strokeLinecap="round" transform="rotate(-90 70 70)"/>
              </svg>
              <div className="ring-center"><div className="mins">{avgWalk}</div><label>min avg/day</label></div>
            </div>
            {petExercise.length===0&&<div className="empty-state"><div className="es-icon">🦮</div><p>No walks logged.</p></div>}
            <div className="walk-log">
              {petExercise.map(w=>(
                <div key={w.id} className="walk-item">
                  <div className="walk-day"><span>{w.day}</span><span>{w.dayName}</span></div>
                  <div className="walk-detail"><strong>{w.route}</strong><span>Started at {w.time}</span></div>
                  <div className="walk-mins">{w.duration}m</div>
                </div>
              ))}
            </div>
          </>
        )}
      </div>
    </div>
  );

  const renderReminders = () => {
    const displayEvents = reminderSubTab==="upcoming" ? upcomingEvents
      : reminderSubTab==="auto" ? sortedEvents.filter(e=>e.isAutoGenerated)
      : sortedEvents.filter(e=>!e.isAutoGenerated);
    return (
      <div className="screen">
        <div className="screen-header">
          <h1>Reminders 🔔</h1>
          <p>{upcomingEvents.length} upcoming · {events.filter(e=>e.isAutoGenerated).length} auto-created</p>
        </div>
        {/* PUSH PERMISSION BANNER — shown when not yet granted */}
        {pushPermission !== "granted" && pushPermission !== "unsupported" && (
          <div className="push-banner">
            <div className="push-banner-icon">🔔</div>
            <div className="push-banner-text">
              <strong>Enable push notifications</strong>
              <span>Get reminders on your phone even when the app is closed</span>
            </div>
            <button className="push-enable-btn" onClick={handleEnablePush}>Enable</button>
          </div>
        )}

        {/* PUSH STATUS ROW — shown when granted */}
        {pushPermission === "granted" && (
          <div className="push-status-row">
            <div className="push-dot on"/>
            <span>Push notifications on · {pushScheduled} reminder{pushScheduled!==1?"s":""} scheduled</span>
            <button onClick={()=>syncNotificationsToSW(events).then(n=>setPushScheduled(n))}>Sync</button>
          </div>
        )}

        {pushPermission === "unsupported" && (
          <div className="push-status-row">
            <div className="push-dot off"/>
            <span>Push notifications not supported in this browser</span>
          </div>
        )}

        <div className="info-banner">
          <span>🤖</span>
          <span>Auto events are created when you log vet visits or vaccines with a next-due date. Tap reminder chips on each event to toggle when you want to be reminded.</span>
        </div>
        <div className="quick-reminder-bar">
          <h4>Quick Add</h4>
          <div className="quick-types">
            {[EVENT_TYPE.WALK,EVENT_TYPE.BATH,EVENT_TYPE.MEDICATION,EVENT_TYPE.CUSTOM].map(t=>{
              const m=EVENT_META[t];
              return(
                <div key={t} className="quick-type-btn" onClick={()=>{setNewReminder(r=>({...r,label:m.label,eventType:t,reminderTimes:DEFAULT_REMINDERS[t]||[1]}));setShowModal("addReminder");}}>
                  <span>{m.icon}</span><span>{m.label}</span>
                </div>
              );
            })}
          </div>
        </div>
        <div className="reminder-tabs">
          {[["upcoming","Upcoming"],["auto","Auto-created"],["custom","Custom"]].map(([k,l])=>(
            <div key={k} className={`reminder-tab ${reminderSubTab===k?"active":""}`} onClick={()=>setReminderSubTab(k)}>{l}</div>
          ))}
        </div>
        <div style={{padding:"0 24px",display:"flex",flexDirection:"column",gap:12,paddingBottom:20}}>
          {displayEvents.length===0&&<div className="empty-state"><div className="es-icon">📭</div><p>Nothing here yet.</p></div>}
          {displayEvents.map(ev=><EventCard key={ev.id} ev={ev}/>)}
        </div>
      </div>
    );
  };

  const renderCalendar = () => {
    const d=new Date(); const year=d.getFullYear(); const month=d.getMonth();
    const firstDay=new Date(year,month,1).getDay();
    const daysInMonth=new Date(year,month+1,0).getDate();
    const todayNum=d.getDate();
    const eventDays=new Set(sortedEvents.map(e=>{const pd=parseDate(e.date);return pd&&pd.getMonth()===month&&pd.getFullYear()===year?pd.getDate():null;}).filter(Boolean));
    return(
      <div className="screen">
        <div className="screen-header"><h1>Calendar 📅</h1><p>All events in one view</p></div>
        <div style={{padding:"0 24px 20px"}}>
          <div className="cal-header">
            <h3>{d.toLocaleDateString("en-US",{month:"long",year:"numeric"})}</h3>
            <div style={{display:"flex",gap:8}}><button className="cal-nav">‹</button><button className="cal-nav">›</button></div>
          </div>
          <div className="cal-grid">
            {["S","M","T","W","T","F","S"].map((x,i)=><div key={i} className="cal-day-label">{x}</div>)}
            {Array.from({length:firstDay}).map((_,i)=><div key={`e${i}`}/>)}
            {Array.from({length:daysInMonth},(_,i)=>{const day=i+1;return<div key={day} className={`cal-day ${day===todayNum?"today":""} ${eventDays.has(day)?"has-event":""}`}>{day}</div>;})}
          </div>
          <div style={{fontSize:13,fontWeight:500,color:"var(--brown)",marginBottom:12}}>All Scheduled ({upcomingEvents.length})</div>
          <div className="cal-events">
            {upcomingEvents.map(ev=>{
              const meta=EVENT_META[ev.eventType]||EVENT_META[EVENT_TYPE.CUSTOM];
              const dl=daysLabel(ev.date);
              return(
                <div key={ev.id} className={`cal-event ${ev.isAutoGenerated?"auto-event":""}`}>
                  <div className="cal-event-color" style={{background:meta.color}}></div>
                  <div className="cal-event-info">
                    <strong>{meta.icon} {ev.label}</strong>
                    <span>{ev.petName} · {fmtDate(parseDate(ev.date))}</span>
                    {ev.isAutoGenerated&&<span className="cal-event-badge">🤖 Auto-scheduled</span>}
                  </div>
                  {dl&&<span className={`event-days-badge ${dl.cls}`} style={{fontSize:10,padding:"2px 8px",borderRadius:20,fontWeight:600,flexShrink:0}}>{dl.text}</span>}
                </div>
              );
            })}
          </div>
        </div>
      </div>
    );
  };

  const renderDocs = () => (
    <div className="screen">
      <div className="screen-header"><h1>Documents 📁</h1><p>All records for {pet?.name}</p></div>
      <div style={{padding:"0 24px"}}>
        <div className="doc-grid">
          {petDocs.map(d=><div key={d.id} className="doc-card"><div className="doc-icon">{d.icon}</div><h3>{d.name}</h3><p>{d.date} · {d.size}</p></div>)}
          <div className="doc-card doc-add"><span style={{fontSize:28}}>＋</span><span>Upload Doc</span></div>
        </div>
      </div>
    </div>
  );

  // ─────────────────────────────────────────────
  //  RENDER
  // ─────────────────────────────────────────────
  return (
    <>
      <style>{style}</style>
      <div className="app">

        {/* TOAST NOTIFICATIONS */}
        <div className="toast-stack">
          {toasts.map(t=>{
            const meta=EVENT_META[t.event.eventType]||EVENT_META[EVENT_TYPE.CUSTOM];
            const msg=t.daysLeft===0?"Today!":t.daysLeft===1?"Tomorrow":`In ${t.daysLeft} days`;
            return(
              <div key={t.id} className="toast">
                <div className="toast-icon">{meta.icon}</div>
                <div className="toast-body">
                  <strong>🔔 {t.event.label}</strong>
                  <span>{t.event.petName} · {msg}</span>
                </div>
                <span className="toast-close" onClick={()=>dismissToast(t.id)}>✕</span>
              </div>
            );
          })}
        </div>

        {/* NOTIFICATION SLIDE-IN PANEL */}
        <div className={`notif-panel ${notifOpen?"open":""}`}>
          <div className="notif-panel-header">
            <h2>🔔 Notifications</h2>
            <span className="notif-panel-close" onClick={()=>setNotifOpen(false)}>✕</span>
          </div>
          <div className="notif-list">
            {upcomingEvents.length===0&&<div className="empty-state"><div className="es-icon">📭</div><p>All clear!</p></div>}
            {upcomingEvents.map(ev=>{
              const meta=EVENT_META[ev.eventType]||EVENT_META[EVENT_TYPE.CUSTOM];
              const dl=daysLabel(ev.date);
              const isFiring=getFiringReminders([ev]).filter(f=>!dismissedSet.has(`${f.event.id}-${f.offset}`)).length>0;
              const tColor=dl?.cls==="badge-today"?"#D32F2F":dl?.cls==="badge-soon"?"#C8853A":"var(--sage)";
              return(
                <div key={ev.id} className={`notif-item ${isFiring?"firing":""}`}>
                  <div className="notif-dot" style={{background:meta.color+"22"}}>{meta.icon}</div>
                  <div className="notif-info">
                    <strong>{ev.label}</strong>
                    <span>{ev.petName}</span>
                    <span>{fmtDate(parseDate(ev.date))}</span>
                    {dl&&<span className="notif-timing" style={{color:tColor}}>{dl.text}</span>}
                    <div style={{display:"flex",gap:6,marginTop:4,flexWrap:"wrap"}}>
                      {ev.reminderTimes.map(o=><span key={o} style={{fontSize:9,background:"var(--warm)",borderRadius:20,padding:"2px 8px",color:"var(--text-soft)"}}>{OFFSET_LABEL[o]}</span>)}
                    </div>
                  </div>
                  {isFiring&&<span className="notif-dismiss" onClick={()=>{const f=getFiringReminders([ev])[0];if(f)dismissToast(`${ev.id}-${f.offset}`);}}>✓</span>}
                </div>
              );
            })}
          </div>
        </div>

        {/* TOPBAR */}
        <div className="topbar">
          <div className="topbar-logo">Paw<span>Keeper</span></div>
          <div className="notif-btn" onClick={()=>setNotifOpen(true)} title={pushPermission==="granted"?"Push notifications active":"Push notifications off"}>
            🔔
            {firingCount>0&&<div className="notif-badge">{firingCount}</div>}
            {pushPermission==="granted"&&firingCount===0&&<div style={{position:"absolute",bottom:-2,right:-2,width:10,height:10,background:"#4CAF50",borderRadius:"50%",border:"2px solid var(--cream)"}}/>}
          </div>
        </div>

        {activeNav==="home"      && renderHome()}
        {activeNav==="profile"   && renderProfile()}
        {activeNav==="reminders" && renderReminders()}
        {activeNav==="calendar"  && renderCalendar()}
        {activeNav==="docs"      && renderDocs()}

        {activeNav==="profile"&&activeTab==="vet"&&<button className="fab" onClick={()=>setShowModal("addVet")}>＋</button>}
        {activeNav==="reminders"&&<button className="fab" onClick={()=>{setNewReminder(r=>({...r,eventType:EVENT_TYPE.CUSTOM,label:"",reminderTimes:[1]}));setShowModal("addReminder");}}>＋</button>}
        {activeNav==="home"&&<button className="fab" onClick={()=>setShowModal("addPet")}>＋</button>}

        <div className="bottom-nav">
          {[["home","🏠","Home"],["profile","🐾","My Pet"],["reminders","🔔","Reminders"],["calendar","📅","Calendar"],["docs","📁","Docs"]].map(([key,icon,label])=>(
            <div key={key} className={`nav-item ${activeNav===key?"active":""}`} onClick={()=>setActiveNav(key)}>
              <span className="nav-icon">{icon}</span>
              <span className="nav-label">{label}</span>
            </div>
          ))}
        </div>

        {/* ── MODALS ── */}

        {showModal==="addVet"&&(
          <div className="modal-overlay" onClick={e=>e.target.className==="modal-overlay"&&(resetScan(),setShowModal(null))}>
            <div className="modal">
              <div className="modal-handle"></div>
              <h2>Log Vet Visit</h2>

              {/* ── SCAN / UPLOAD BUTTONS ── */}
              {scanState==="idle"&&!scanImageURL&&(
                <>
                  <div className="scan-btns">
                    <button className="scan-btn primary" onClick={handleScanCamera}>
                      <span>📷</span><span>Scan Prescription</span>
                    </button>
                    <button className="scan-btn" onClick={handleScanUpload}>
                      <span>📁</span><span>Upload Prescription</span>
                    </button>
                  </div>
                  <div className="ocr-divider"><span>or fill manually</span></div>
                </>
              )}

              {/* ── IMAGE PREVIEW ── */}
              {scanImageURL&&(
                <div className="scan-preview">
                  <img src={scanImageURL} alt="Prescription preview"/>
                  <button className="scan-preview-remove" onClick={resetScan}>✕</button>
                </div>
              )}

              {/* ── PROCESSING STATE ── */}
              {scanState==="processing"&&(
                <div className="scan-processing">
                  <div className="scan-spinner"/>
                  <span>Extracting prescription details…</span>
                </div>
              )}

              {/* ── RESULT BANNERS ── */}
              {scanState==="done"&&(
                <div className="scan-result-banner success">
                  <span>✅</span>
                  <span>Fields auto-filled from prescription. Please review before saving.</span>
                </div>
              )}
              {scanState==="done"&&Object.values(ocrFields).some(c=>c===CONF.LOW||c===CONF.MISSING)&&(
                <div className="scan-result-banner warn">
                  <span>⚠️</span>
                  <span>Some fields could not be clearly detected — highlighted in yellow. Please verify.</span>
                </div>
              )}
              {scanState==="error"&&(
                <div className="scan-result-banner error">
                  <span>❌</span>
                  <span>Unable to extract details from this image. Please fill in manually.</span>
                </div>
              )}

              {/* ── REVIEW BADGE (shown when autofilled) ── */}
              {scanState==="done"&&(
                <div className="review-badge">📋 Review autofilled data before saving</div>
              )}

              {/* ── FORM FIELDS (existing, with confidence styling) ── */}
              {scanState!=="processing"&&(
                <>
                  <div className="form-row">
                    <div className={`form-group ${fieldClass("date")}`}>
                      <label>Date</label>
                      <input type="date" value={newVet.date} onChange={e=>setNewVet(v=>({...v,date:e.target.value}))}/>
                      {ocrFields.date===CONF.LOW&&<div className="field-warn-msg">⚠ Couldn't clearly detect this field, please verify</div>}
                    </div>
                    <div className={`form-group ${fieldClass("clinic")}`}>
                      <label>Clinic</label>
                      <input placeholder="e.g. PawCare" value={newVet.clinic} onChange={e=>setNewVet(v=>({...v,clinic:e.target.value}))}/>
                      {ocrFields.clinic===CONF.LOW&&<div className="field-warn-msg">⚠ Couldn't clearly detect this field, please verify</div>}
                    </div>
                  </div>
                  <div className={`form-group ${fieldClass("location")}`}>
                    <label>Location</label>
                    <input value={newVet.location} onChange={e=>setNewVet(v=>({...v,location:e.target.value}))}/>
                    {ocrFields.location===CONF.LOW&&<div className="field-warn-msg">⚠ Couldn't clearly detect this field, please verify</div>}
                  </div>
                  <div className={`form-group ${fieldClass("doctor")}`}>
                    <label>Doctor</label>
                    <input placeholder="Dr. Name" value={newVet.doctor} onChange={e=>setNewVet(v=>({...v,doctor:e.target.value}))}/>
                    {ocrFields.doctor===CONF.LOW&&<div className="field-warn-msg">⚠ Couldn't clearly detect this field, please verify</div>}
                    {ocrFields.doctor===CONF.MISSING&&scanState==="done"&&<div className="field-warn-msg">⚠ Couldn't clearly detect this field, please verify or enter manually</div>}
                  </div>
                  <div className={`form-group ${fieldClass("reason")}`}>
                    <label>Reason</label>
                    <input value={newVet.reason} onChange={e=>setNewVet(v=>({...v,reason:e.target.value}))}/>
                    {ocrFields.reason===CONF.LOW&&<div className="field-warn-msg">⚠ Couldn't clearly detect this field, please verify</div>}
                  </div>
                  <div className={`form-group ${fieldClass("diagnosis")}`}>
                    <label>Diagnosis</label>
                    <textarea rows={2} value={newVet.diagnosis} onChange={e=>setNewVet(v=>({...v,diagnosis:e.target.value}))}/>
                    {ocrFields.diagnosis===CONF.LOW&&<div className="field-warn-msg">⚠ Couldn't clearly detect this field, please verify</div>}
                  </div>
                  <div className={`form-group ${fieldClass("meds")}`}>
                    <label>Medications (comma separated)</label>
                    <input value={newVet.meds} onChange={e=>setNewVet(v=>({...v,meds:e.target.value}))}/>
                    {ocrFields.meds===CONF.LOW&&<div className="field-warn-msg">⚠ Couldn't clearly detect this field, please verify</div>}
                  </div>
                  <div className={`form-group ${fieldClass("nextVisit")}`}>
                    <label>Next Visit Recommended</label>
                    <input type="date" value={newVet.nextVisit} onChange={e=>setNewVet(v=>({...v,nextVisit:e.target.value}))}/>
                    {ocrFields.nextVisit===CONF.LOW&&<div className="field-warn-msg">⚠ Couldn't clearly detect this field, please verify</div>}
                    {newVet.nextVisit&&<div style={{fontSize:11,color:"var(--sage)",marginTop:6}}>
                      🤖 Calendar event will be auto-created with reminders 2 days before &amp; same day
                    </div>}
                  </div>

                  {/* ── GOOGLE CALENDAR BUTTON (shown when nextVisit is set) ── */}
                  {newVet.nextVisit&&(()=>{
                    const gcalUrl = buildGCalURL({
                      title: `🐾 ${pet?.name} – Vet Visit${newVet.clinic ? " at " + newVet.clinic : ""}`,
                      date:  newVet.nextVisit,
                      description: [
                        newVet.doctor   ? `Doctor: ${newVet.doctor}`    : "",
                        newVet.location ? `Location: ${newVet.location}` : "",
                        newVet.diagnosis? `Diagnosis: ${newVet.diagnosis}` : "",
                      ].filter(Boolean).join("\n")
                    });
                    return gcalUrl ? (
                      <a href={gcalUrl} target="_blank" rel="noopener noreferrer" style={{textDecoration:"none"}}>
                        <button className="gcal-btn">
                          <svg width="16" height="16" viewBox="0 0 24 24" fill="none">
                            <rect x="3" y="4" width="18" height="17" rx="2" stroke="#4285F4" strokeWidth="2"/>
                            <path d="M3 9h18" stroke="#4285F4" strokeWidth="2"/>
                            <path d="M8 2v4M16 2v4" stroke="#4285F4" strokeWidth="2" strokeLinecap="round"/>
                            <rect x="7" y="13" width="3" height="3" rx="0.5" fill="#4285F4"/>
                            <rect x="11" y="13" width="3" height="3" rx="0.5" fill="#EA4335"/>
                            <rect x="15" y="13" width="3" height="3" rx="0.5" fill="#FBBC04"/>
                          </svg>
                          Add to Google Calendar
                        </button>
                      </a>
                    ) : null;
                  })()}

                  <button className="btn-primary" onClick={handleAddVet}>
                    {scanState==="done" ? "✓ Confirm & Save Visit" : "Save Visit"}
                  </button>
                  <button className="btn-secondary" onClick={()=>{resetScan();setShowModal(null);}}>Cancel</button>
                </>
              )}
            </div>
          </div>
        )}

        {showModal==="addReminder"&&(
          <div className="modal-overlay" onClick={e=>e.target.className==="modal-overlay"&&setShowModal(null)}>
            <div className="modal">
              <div className="modal-handle"></div>
              <h2>Add Reminder</h2>
              <div className="form-group">
                <label>Type</label>
                <div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:4}}>
                  {Object.entries(EVENT_META).map(([t,m])=>(
                    <span key={t} onClick={()=>setNewReminder(r=>({...r,eventType:t,reminderTimes:DEFAULT_REMINDERS[t]||[1]}))}
                      style={{padding:"6px 14px",borderRadius:20,fontSize:12,cursor:"pointer",border:"1.5px solid",
                        borderColor:newReminder.eventType===t?"var(--amber)":"var(--border)",
                        background:newReminder.eventType===t?"#FFF3E0":"var(--card)",
                        color:newReminder.eventType===t?"var(--amber)":"var(--text-soft)"}}>
                      {m.icon} {m.label}
                    </span>
                  ))}
                </div>
              </div>
              <div className="form-group"><label>Label</label><input placeholder="e.g. Morning Walk, Flea treatment" value={newReminder.label} onChange={e=>setNewReminder(r=>({...r,label:e.target.value}))}/></div>
              <div className="form-row">
                <div className="form-group"><label>Date</label><input type="date" value={newReminder.date} onChange={e=>setNewReminder(r=>({...r,date:e.target.value}))}/></div>
                <div className="form-group"><label>For Pet</label>
                  <select value={newReminder.petId} onChange={e=>setNewReminder(r=>({...r,petId:parseInt(e.target.value)}))}>
                    {pets.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}
                  </select>
                </div>
              </div>
              <div className="form-group">
                <label>Remind Me</label>
                <div className="offset-picker">
                  {OFFSET_OPTIONS.map(o=>(
                    <span key={o} className={`offset-chip ${newReminder.reminderTimes.includes(o)?"on":""}`}
                      onClick={()=>setNewReminder(r=>({...r,reminderTimes:r.reminderTimes.includes(o)?r.reminderTimes.filter(x=>x!==o):[...r.reminderTimes,o]}))}>
                      {OFFSET_LABEL[o]}
                    </span>
                  ))}
                </div>
              </div>
              <button className="btn-primary" onClick={handleAddReminder}>Save Reminder</button>
              <button className="btn-secondary" onClick={()=>setShowModal(null)}>Cancel</button>
            </div>
          </div>
        )}

        {showModal==="addPet"&&(
          <div className="modal-overlay" onClick={e=>e.target.className==="modal-overlay"&&setShowModal(null)}>
            <div className="modal">
              <div className="modal-handle"></div>
              <h2>Add New Pet</h2>
              <div className="form-group"><label>Avatar</label></div>
              <div className="emoji-picker">{EMOJIS.map(em=><span key={em} className={`emoji-opt ${newPet.emoji===em?"selected":""}`} onClick={()=>setNewPet(v=>({...v,emoji:em}))}>{em}</span>)}</div>
              <div className="form-group"><label>Name</label><input value={newPet.name} onChange={e=>setNewPet(v=>({...v,name:e.target.value}))}/></div>
              <div className="form-group"><label>Breed / Type</label><input value={newPet.breed} onChange={e=>setNewPet(v=>({...v,breed:e.target.value}))}/></div>
              <div className="form-row">
                <div className="form-group"><label>Age</label><input value={newPet.age} onChange={e=>setNewPet(v=>({...v,age:e.target.value}))}/></div>
                <div className="form-group"><label>Gender</label>
                  <select value={newPet.gender} onChange={e=>setNewPet(v=>({...v,gender:e.target.value}))}><option>Male</option><option>Female</option></select>
                </div>
              </div>
              <div className="form-group"><label>Birthday</label><input type="date" value={newPet.birthday} onChange={e=>setNewPet(v=>({...v,birthday:e.target.value}))}/></div>
              <button className="btn-primary" onClick={handleAddPet}>Add Pet</button>
              <button className="btn-secondary" onClick={()=>setShowModal(null)}>Cancel</button>
            </div>
          </div>
        )}

        {showModal==="editPet"&&editPetData&&(
          <div className="modal-overlay" onClick={e=>e.target.className==="modal-overlay"&&setShowModal(null)}>
            <div className="modal">
              <div className="modal-handle"></div>
              <h2>Edit {pet?.name}'s Profile</h2>
              <div className="form-group"><label>Avatar</label></div>
              <div className="emoji-picker">{EMOJIS.map(em=><span key={em} className={`emoji-opt ${editPetData.emoji===em?"selected":""}`} onClick={()=>setEditPetData(v=>({...v,emoji:em}))}>{em}</span>)}</div>
              <div className="form-group"><label>Name</label><input value={editPetData.name} onChange={e=>setEditPetData(v=>({...v,name:e.target.value}))}/></div>
              <div className="form-group"><label>Breed / Type</label><input value={editPetData.breed} onChange={e=>setEditPetData(v=>({...v,breed:e.target.value}))}/></div>
              <div className="form-row">
                <div className="form-group"><label>Age</label><input value={editPetData.age} onChange={e=>setEditPetData(v=>({...v,age:e.target.value}))}/></div>
                <div className="form-group"><label>Gender</label>
                  <select value={editPetData.gender} onChange={e=>setEditPetData(v=>({...v,gender:e.target.value}))}><option>Male</option><option>Female</option></select>
                </div>
              </div>
              <div className="form-group"><label>Birthday</label><input value={editPetData.birthday} onChange={e=>setEditPetData(v=>({...v,birthday:e.target.value}))}/></div>
              <div className="form-group"><label>Next Vet Visit</label><input value={editPetData.nextVet} onChange={e=>setEditPetData(v=>({...v,nextVet:e.target.value}))}/></div>
              <button className="btn-primary" onClick={handleSaveEditPet}>Save Changes</button>
              <button className="btn-secondary" onClick={()=>setShowModal(null)}>Cancel</button>
            </div>
          </div>
        )}

      </div>
    </>
  );
}
